//File Generated By TelemetryFromXTCE.py

#ifndef ADBTELEMETRYCONTAINER_H_
#define ADBTELEMETRYCONTAINER_H_

#include "TelemetryContainer.h"

#define ADB_CONTAINER_SIZE  16

class ADBTelemetryContainer : public TelemetryContainer
{
protected:
unsigned char telemetry[ADB_CONTAINER_SIZE];

public:
    virtual int size();
    virtual unsigned char * getArray();

    unsigned long getUptime();
    void setUptime(unsigned long var);

    short getBootCounter();
    void setBootCounter(short var);

    char getSoftwareBootCounter();
    void setSoftwareBootCounter(char var);

    bool getADB_INA_Status();
    void setADB_INA_Status(bool var);

    bool getADB_TMP_Status();
    void setADB_TMP_Status(bool var);

    short getADBCurrent();
    void setADBCurrent(short var);

    short getADBVoltage();
    void setADBVoltage(short var);

    short getADBTemperature();
    void setADBTemperature(short var);

    short getMCUTemp();
    void setMCUTemp(short var);

};

#endif /* ADBTELEMETRYCONTAINER_H_ */
