//File Generated By TelemetryFromXTCE.py

#ifndef ADBTELEMETRYCONTAINER_H_
#define ADBTELEMETRYCONTAINER_H_

#include "TelemetryContainer.h"

#define ADB_CONTAINER_SIZE  24

class ADBTelemetryContainer : public TelemetryContainer
{
protected:
unsigned char telemetry[ADB_CONTAINER_SIZE];

public:
    virtual int size();
    virtual unsigned char * getArray();

    char getStatus();
    void setStatus(char var);

    char getBootCounter();
    void setBootCounter(char var);

    long getResetCause();
    void setResetCause(long var);

    unsigned long getUptime();
    void setUptime(unsigned long var);

    unsigned long getTotalUptime();
    void setTotalUptime(unsigned long var);

    char getVersionNumber();
    void setVersionNumber(char var);

    short getMCUTemp();
    void setMCUTemp(short var);

    bool getADB_INA_Status();
    void setADB_INA_Status(bool var);

    bool getADB_TMP_Status();
    void setADB_TMP_Status(bool var);

    short getADBCurrent();
    void setADBCurrent(short var);

    short getADBVoltage();
    void setADBVoltage(short var);

    short getADBTemperature();
    void setADBTemperature(short var);

};

#endif /* ADBTELEMETRYCONTAINER_H_ */
